### ISSUE TITLE
Cannot build DDS with alibuild (alfadist)

### ISSUE THREAD

**Issue by mvala** [FairRootGroup/alfadist#14]
```
-- Using BOOST Library dir: /cvmfs/hybrilit.jinr.ru/sw/slc7_x86-64/boost/v1.67.0_FAIRROOT-1/lib                                                                                                                     
-- prerequisite dirs: /cvmfs/hybrilit.jinr.ru/sw/slc7_x86-64/boost/v1.67.0_FAIRROOT-1/lib;/cvmfs/hybrilit.jinr.ru/sw/BUILD/4666d0c0c476995f137a51a0d17ae32fdc7dd7f8/DDS/dds-user-defaults;/cvmfs/hybrilit.jinr.ru/sw
/BUILD/4666d0c0c476995f137a51a0d17ae32fdc7dd7f8/DDS/dds-protocol-lib;/cvmfs/hybrilit.jinr.ru/sw/BUILD/4666d0c0c476995f137a51a0d17ae32fdc7dd7f8/DDS/dds-intercom-lib;/cvmfs/hybrilit.jinr.ru/sw/BUILD/4666d0c0c476995
f137a51a0d17ae32fdc7dd7f8/DDS/dds-topology-lib;/cvmfs/hybrilit.jinr.ru/sw/BUILD/4666d0c0c476995f137a51a0d17ae32fdc7dd7f8/DDS/MiscCommon/dds_ncf;                                                                    
WN PKG prerequisite='/cvmfs/hybrilit.jinr.ru/sw/BUILD/4666d0c0c476995f137a51a0d17ae32fdc7dd7f8/DDS/dds-intercom-lib/libdds_intercom_lib.so'                                                                         
WN PKG prerequisite='/cvmfs/hybrilit.jinr.ru/sw/BUILD/4666d0c0c476995f137a51a0d17ae32fdc7dd7f8/DDS/dds-protocol-lib/libdds_protocol_lib.so'                                                                         
WN PKG prerequisite='/cvmfs/hybrilit.jinr.ru/sw/BUILD/4666d0c0c476995f137a51a0d17ae32fdc7dd7f8/DDS/dds-user-defaults/libdds-user-defaults.so'                                                                       
--                                                                                                                                                                                                                  
warning: cannot resolve item 'libgcc_s.so.1'                                                                                                                                                                        
                                                                                                                                                                                                                    
  possible problems:                                                                                                                                                                                                
    need more directories?                                                                                                                                                                                          
    need to use InstallRequiredSystemLibraries?                                                                                                                                                                     
    run in install tree instead of build tree?                                                                                                                                                                      
                                                                                                                                                                                                                    
WN PKG prerequisite='libgcc_s.so.1'                                                                                                                                                                                 
CMake Error at /cvmfs/hybrilit.jinr.ru/sw/SOURCES/DDS/2.1/2.1/cmake/modules/DDS_CollectPrerequisites.cmake:33 (file):                                                                                               
  file COPY cannot find                                                                                                                                                                                             
  "/cvmfs/hybrilit.jinr.ru/sw/BUILD/4666d0c0c476995f137a51a0d17ae32fdc7dd7f8/DDS/libgcc_s.so.1".                                                                                                                    
                                                                                                                                                                                                                    
                                                                                                                                                                                                                    
gmake[3]: *** [CMakeFiles/wn_bin] Error 1                                                                                                                                                                           
gmake[2]: *** [CMakeFiles/wn_bin.dir/all] Error 2                                                                                                                                                                   
gmake[1]: *** [CMakeFiles/wn_bin.dir/rule] Error 2                                                                                                                                                                  
gmake: *** [wn_bin] Error 2          
```

**Comment by mvala** [comment]
I am using following defaults file
```
package: defaults-fairroot                                                                                                                                                                                          
version: v1                                                                                                                                                                                                         
env:                                                                                                                                                                                                                
  CXX_STANDARD: "11"                                                                                                                                                                                                
  CXXFLAGS: "-fPIC"                                                                                                                                                                                                 
  CFLAGS: "-fPIC"                                                                                                                                                                                                   
  CMAKE_BUILD_TYPE: "RELWITHDEBINFO"                                                                                                                                                                                
overrides:                                                                                                                                                                                                          
  GCC-Toolchain:                                                                                                                                                                                                    
    tag: v6.2.0-alice1                                                                                                                                                                                              
  DDS:                                                                                                                                                                                                              
    tag: 2.1                                                                                                                                                                                                        
---    
```
